// <auto-generated />
using System;
using EmpreendedorismoSC.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpreendedorismoSC.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EmpreendedorismoSC.Domain.Entities.Empreendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeEmpreendedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeEmpreendimento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentoAtuacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("Municipio");

                    b.HasIndex("SegmentoAtuacao");

                    b.ToTable("Empreendimentos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Ativo = true,
                            Contato = "marina@techfloripahub.com.br",
                            DataCriacao = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Municipio = "Florianópolis",
                            NomeEmpreendedor = "Marina Costa",
                            NomeEmpreendimento = "Tech Floripa Hub",
                            SegmentoAtuacao = "Tecnologia"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Ativo = true,
                            Contato = "roberto@comerciodovale.com.br",
                            DataCriacao = new DateTime(2024, 2, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            Municipio = "Blumenau",
                            NomeEmpreendedor = "Roberto Schneider",
                            NomeEmpreendimento = "Comércio do Vale",
                            SegmentoAtuacao = "Comercio"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            Ativo = true,
                            Contato = "ana@joinvilletextil.com.br",
                            DataCriacao = new DateTime(2024, 3, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Municipio = "Joinville",
                            NomeEmpreendedor = "Ana Müller",
                            NomeEmpreendimento = "Indústria Joinville Têxtil",
                            SegmentoAtuacao = "Industria"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            Ativo = false,
                            Contato = "pedro@consultoriaserra.com.br",
                            DataCriacao = new DateTime(2024, 4, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            Municipio = "Lages",
                            NomeEmpreendedor = "Pedro Souza",
                            NomeEmpreendimento = "Consultoria Serra Catarinense",
                            SegmentoAtuacao = "Servicos"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-efab-345678901234"),
                            Ativo = true,
                            Contato = "carla@agrooestesc.com.br",
                            DataCriacao = new DateTime(2024, 5, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            Municipio = "Chapecó",
                            NomeEmpreendedor = "Carla Fernandes",
                            NomeEmpreendimento = "Agro Oeste SC",
                            SegmentoAtuacao = "Agronegocio"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
